apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: github-secret-scanning
  description: GitHub secret scanning alert service
  labels:
    license: MIT
spec:
  type: service
  lifecycle: experimental
  owner: group:cds-snc/internal-sre
  domain: site-reliability-engineering
  system: cds-alm
