apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: github-secret-scanning
  description: GitHub secret scanning alert service
  labels:
    license: MIT
spec:
  type: website
  lifecycle: experimental
  owner: cds-snc
