skip-check:
  - CKV_AWS_51 # ECR: `latest` tag is used for development
  - CKV_AWS_117 # Lambda: access to VPC resources not required
  - CKV_AWS_136 # ECR: default encryption key is acceptable
  - CKV_AWS_158 # CloudWatch: default encryption key is acceptable
