name: Lint, format and test code
on:
  pull_request:
    branches:
      - main
    paths:
      - api/**
      - .github/workflows/ci-code.yml

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0

      - name: Setup python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.14"

      - name: Install dependencies
        working-directory: ./api
        run: |
          make install
          make install-dev

      - name: Lint
        working-directory: ./api
        run: make lint-ci

      - name: Format
        working-directory: ./api
        run: make fmt-ci

      - name: Test
        working-directory: ./api
        run: make test
